version: '3'
services:
 nginx:
  image: nginx
  ports:
  - "80:80"

 db:
  image: mysql:5.7
  environment:
   MYSQL_DATABASE: nba_data
   MYSQL_ROOT_PASSWORD: wearecloudbase!
  ports:
  - "3300:3300"
 web:
  build: .
  command: python CloudBase/Backend_/src/manage.py runserver 0.0.0.0:8000
  volumes:
  - .:/code
  ports:
  - "8000:8000"
  depends_on:
  - db
  links:
  - db
  - elasticsearch

 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
  ports:
  - "9200:9200"
  environment:
  - cluster.name=docker-cluster
  - bootstrap.memory_lock=true
  - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
   memlock:
    soft: -1
    hard: -1